#!/bin/bash

# Get the name of the branch being pushed to
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# Check if the branch name matches the pattern
if [[ "$BRANCH_NAME" =~ ^release/changed-elements-react-v[0-9a-zA-Z]+\.[0-9a-zA-Z]+\.[0-9a-zA-Z]+$ ]]; then
  # Extract version from CHANGELOG.md
  VERSION=$(grep -oP '^## \K[0-9]+\.[0-9]+\.[0-9]+' packages/changed-elements-react/CHANGELOG.md | head -1)

  # Extract version from package.json
  PACKAGE_VERSION=$(grep -oP '"version": "\K[0-9]+\.[0-9]+\.[0-9]+' packages/changed-elements-react/package.json)

  # Compare versions
  if [ "$VERSION" != "$PACKAGE_VERSION" ]; then
    echo "Package version: $PACKAGE_VERSION"
    echo "CHANGELOG version: $VERSION"
    echo "Version mismatch: CHANGELOG.md version ($VERSION) does not match package.json version ($PACKAGE_VERSION). Please run npx changeset version. Then run again. For more details read publish_readme.md"
    exit 1
  fi

  # Extract major and minor version from branch name
  BRANCH_VERSION=$(echo "$BRANCH_NAME" | grep -oP 'v\K[0-9]+\.[0-9]+')

  # Extract major and minor version from package.json and CHANGELOG.md
  PACKAGE_MAJOR_MINOR=$(echo "$PACKAGE_VERSION" | grep -oP '^[0-9]+\.[0-9]+')
  CHANGELOG_MAJOR_MINOR=$(echo "$VERSION" | grep -oP '^[0-9]+\.[0-9]+')

  # Compare branch major.minor version with package and changelog major.minor versions
  if [ "$BRANCH_VERSION" != "$PACKAGE_MAJOR_MINOR" ] || [ "$BRANCH_VERSION" != "$CHANGELOG_MAJOR_MINOR" ]; then
    echo "Branch major.minor version: $BRANCH_VERSION"
    echo "Package major.minor version: $PACKAGE_MAJOR_MINOR"
    echo "CHANGELOG major.minor version: $CHANGELOG_MAJOR_MINOR"
    echo "Version mismatch: release branch major.minor version ($BRANCH_VERSION) does not equal CHANGELOG.md major.minor version ($CHANGELOG_MAJOR_MINOR) or package.json major.minor version ($PACKAGE_MAJOR_MINOR). Please run npx changeset version. Then run again. For more details read publish_readme.md"
    exit 1
  fi
fi
