trigger:
  tags:
    include:
      - v*.*.*

pr: none

variables:
  - name: packageName
    value: changed-elements-react
  - name: packageVersion
    value: ${{ replace(variables['Build.SourceBranchName'], 'v', '') }}
  - name: tarballName
    value: itwin-$(packageName)-$(packageVersion).tgz

resources:
  repositories:
    - repository: templates
      type: git
      name: iModelTechnologies/imodeljs-build-pipeline-scripts

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: Build
        steps:
          - checkout: self
            clean: true
            fetchDepth: 1

          - task: NodeTool@0
            displayName: Use Node.js 18.x
            inputs:
              versionSpec: 18.x

          - task: CmdLine@2
            displayName: Install pnpm
            inputs:
              script: npm install -g pnpm

          - task: CmdLine@2
            displayName: Audit
            inputs:
              script: pnpm audit --audit-level=high

          - task: CmdLine@2
            displayName: Install dependencies
            inputs:
              script: pnpm install --filter $(packageName)

          - task: CmdLine@2
            displayName: Build package
            inputs:
              script: npm run build
              workingDirectory: packages/$(packageName)/

          - task: CmdLine@2
            displayName: Run unit tests
            inputs:
              script: npm run test:cover
              workingDirectory: packages/$(packageName)/

          - task: CmdLine@2
            displayName: Pack package files
            inputs:
              script: pnpm pack
              workingDirectory: packages/$(packageName)/

          - publish: packages/$(packageName)/$(tarballName)
            displayName: Publish package artifact
            artifact: published-package

  - stage: publish
    dependsOn: build
    displayName: Publish
    jobs:
      - job: Publish
        steps:
          - checkout: self
            clean: true
            fetchDepth: 1

          - task: NodeTool@0
            displayName: Use Node.js 18.x
            inputs:
              versionSpec: 18.x

          - task: CmdLine@2
            displayName: Install pnpm
            inputs:
              script: npm install -g pnpm

          - task: CmdLine@2
            displayName: Bump version and update changelog
            inputs:
              script: |
                VERSION_TYPE=$(echo "${{ variables['Build.SourceBranchName'] }}" | sed -E 's/refs\/tags\/v([0-9]+)\.([0-9]+)\.([0-9]+)/\1.\2.\3/')
                npm version $VERSION_TYPE --no-git-tag-version
                PACKAGE_VERSION=$(node -p "require('./package.json').version")
                sed -i "s/## \[Unreleased\]/## [Unreleased]\n\n## [$PACKAGE_VERSION] - $(date +'%Y-%m-%d')/" CHANGELOG.md

          - task: CmdLine@2
            displayName: Commit changes
            inputs:
              script: |
                git config --global user.name 'github-actions[bot]'
                git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                git add package.json CHANGELOG.md
                git commit -m "chore(release): $PACKAGE_VERSION"
                git tag "v$PACKAGE_VERSION"
                git push origin HEAD --tags

          - template: templates/npmjs-publish-deployment.yaml@templates
            parameters:
              path: $(tarballName)
              artifactName: published-package
