name: CI

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Install pnpm@10.12.4
      uses: pnpm/action-setup@v2
      with:
        version: 10.12.4
        run_install: false

    - name: Use Node.js 20.16.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.16.0
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: ESLint
      run: pnpm run lint --max-warnings 0

    - name: Typecheck
      run: pnpm run typecheck

    - name: Check changed-elements-react unit test coverage
      run: pnpm run cover:components

    - name: Run Audit
      run: pnpm audit --audit-level high

    - name: Check if changeset is present
      if: github.actor != 'imodeljs-admin'
      run: |
        # There are issues with changesets in github workflows, so we need to force pull the master branch
        # Fix for issue https://github.com/changesets/changesets/issues/517#issuecomment-884778604
        git pull -f origin master:master
        pnpm changeset status --since=master
