name: CI

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    name: Build and run tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Check if changeset is present
      run: npx changeset status
