name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install

    - name: ESLint
      run: pnpm run lint

    - name: Typecheck
      run: pnpm run typecheck

    - name: Check changed-elements-react unit test coverage
      run: npm run test:cover --prefix ./packages/changed-elements-react

    - name: Run Audit
      run: pnpm audit --audit-level high

    - name: Create release PR or publish to npm
      id: changesets
      uses: changesets/action@v1
      with:
        publish: pnpm run build:components && pnpm changeset publish
        title: Release packages [publish docs]
        commit: Release packages [publish docs]
        createGithubReleases: true
      env:
        GITHUB_TOKEN: ${{ secrets.IMJS_ADMIN_GH_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}
        GIT_AUTHOR_NAME: imodeljs-admin
        GIT_AUTHOR_EMAIL: imodeljs-admin@users.noreply.github.com

    - name: Log Changesets Outputs
      run: |
        echo "Published: ${{ steps.changesets.outputs.published }}"
        echo "Published Packages: ${{ steps.changesets.outputs.publishedPackages }}"
        echo "Has Changesets: ${{ steps.changesets.outputs.hasChangesets }}"
        echo "Pull Request Number: ${{ steps.changesets.outputs.pullRequestNumber }}"
